version: "3.8"

services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      url: ${URL}
      database__client: mysql
      database__connection__host: ${DB_HOST}
      database__connection__user: ghost-user
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ghost_db
      mail__transport: mailgun
      mail__options__domain: ${MAILGUN_DOMAIN}
      mail__options__api_key: ${MAILGUN_API}
      mail__from: ${MAIL_FROM}
    volumes:
      - ./content:/var/lib/ghost/content
