services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      url: ${URL}
      database__client: mysql
      database__connection__host: ${DB_HOST}
      database__connection__user: ghost-user
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ghost_db
      mail__transport: Direct
      mail__from: ${MAIL_FROM:-noreply@localhost}
    volumes:
      - ./content:/var/lib/ghost/content
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:2368/ghost/api/admin/site/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
